"""create tables

Revision ID: 1fba18c12247
Revises: 
Create Date: 2026-09-17 12:04:22.374958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fba18c12247'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weather_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('temperature_2m_max', sa.Float(), nullable=False),
    sa.Column('temperature_2m_min', sa.Float(), nullable=False),
    sa.Column('precipitation_sum', sa.Integer(), nullable=False),
    sa.Column('precipitation_probability_max', sa.Integer(), nullable=False),
    sa.Column('windspeed_10m_max', sa.Float(), nullable=False),
    sa.Column('windgusts_10m_max', sa.Float(), nullable=False),
    sa.Column('weathercode', sa.Integer(), nullable=False),
    sa.Column('temperature_category', sa.String(), nullable=True),
    sa.Column('precipitation_category', sa.String(), nullable=True),
    sa.Column('wind_speed_category', sa.String(), nullable=True),
    sa.Column('is_rainy', sa.Boolean(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('forecast_runs', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city_id', 'date', name='uix_city_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather_forecasts')
    op.drop_table('cities')
    # ### end Alembic commands ###
