"""add unique to name in city table

Revision ID: b581c329faeb
Revises: 1fba18c12247
Create Date: 2026-09-17 21:42:41.219869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b581c329faeb'
down_revision: Union[str, Sequence[str], None] = '1fba18c12247'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('city_name_unique', 'cities', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('city_name_unique', 'cities', type_='unique')
    # ### end Alembic commands ###
